/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package ubc.cs.cpsc210.sustainabilityapp;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int transparent=0x7f050003;
        public static final int ubcblue=0x7f050000;
        public static final int ubcgrey=0x7f050001;
        public static final int white=0x7f050002;
    }
    public static final class dimen {
        public static final int text_large=0x7f060000;
    }
    public static final class drawable {
        public static final int adefault=0x7f020000;
        public static final int features_selected=0x7f020001;
        public static final int features_unselected=0x7f020002;
        public static final int ic_menu_globe=0x7f020003;
        public static final int ic_menu_light=0x7f020004;
        public static final int ic_menu_tags=0x7f020005;
        public static final int ic_tab_feature=0x7f020006;
        public static final int ic_tab_map=0x7f020007;
        public static final int ic_tab_poi=0x7f020008;
        public static final int icon=0x7f020009;
        public static final int map_pin_blue=0x7f02000a;
        public static final int map_pin_green=0x7f02000b;
        public static final int map_pin_star=0x7f02000c;
        public static final int map_pin_walk=0x7f02000d;
        public static final int map_selected=0x7f02000e;
        public static final int map_unselected=0x7f02000f;
        public static final int place_selected=0x7f020010;
        public static final int place_unselected=0x7f020011;
    }
    public static final class id {
        public static final int mapcontent=0x01010001;
        public static final int realtabcontent=0x01010000;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f070001;
        public static final int hello=0x7f070000;
        public static final int no_network=0x7f070003;
        public static final int ok_btn=0x7f070002;
        public static final int rs_blank=0x7f070006;
        public static final int rs_label=0x7f070005;
        public static final int rs_na_label=0x7f070004;
    }
    public static final class style {
        public static final int UBCStyle=0x7f040000;
    }
}
